sudo: true
language: cpp
dist: trusty

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-5
  sonarcloud:
# See https://docs.travis-ci.com/user/sonarcloud/
    organization: "dstrelak-github"
    token:
        secure: $SONAR_TOKEN

before_install:
 - sudo apt-get install -y libfftw3-dev libopenmpi-dev openmpi-bin libhdf5-dev python-numpy
script: 
 - python ./scripts/travis_before_script
 - python ./xmipp get_devel_sources
 - python ./xmipp config
 - python ./xmipp check_config
 - mkdir -p ./src/xmippCore/install && cp xmipp.conf ./src/xmippCore/install/ && pushd ./src/xmippCore && build-wrapper-linux-x86-64 --out-dir ../../bw-outputs scons
 - popd
 - mkdir -p ./src/xmipp/install && cp xmipp.conf ./src/xmipp/install/ && pushd ./src/xmipp && build-wrapper-linux-x86-64 --out-dir ../../bw-outputs scons
 - popd
 - mkdir -p ./src/xmippViz/install && cp xmipp.conf ./src/xmippViz/install/ && pushd ./src/xmippViz && build-wrapper-linux-x86-64 --out-dir ../../bw-outputs scons
 - popd
 - sonar-scanner
