sudo: true
language: cpp
dist: trusty
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-5
before_install:
 - sudo apt-get install -y libfftw3-dev libopenmpi-dev
script: 
 - python ./scripts/travis_before_script
 - python ./xmipp
